allowLocalFiles: true
options:
  looseYAML: false
  markdown:
    breaks: true       # newlines in paragraphs are rendered as <br>
bespoke:
  progress: true
output: "./build/"
themeSet: "./themes"
theme: tum
