services: docker
dist: bionic

env:
  - DOCKER_COMPOSE_VERSION=1.27.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - mkdir -p build
  - docker-compose run generate --input-dir ./slides"
  - docker-compose run generate --input-dir ./slides --pdf"
  - echo '# This branch is for deployment only' >> build/README.md

# Deploy to gh-pages branch
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: build
  on:
    branch: master

notifications:
  email: false
